### ISSUE TITLE
Example Azure DevOps pipeline to publish the images to dockerhub

### ISSUE THREAD

**Issue by tarunaroraonline** [RobertoPrevato/AzureDevOps-agents#7]
Great work and thanks for maintaining this repo...  

I was wondering if you can provide some code snippets that will help me create an Azure Pipeline to publish all the ubuntu18.04 based images to my private registry in dockerhub?

**Comment by RobertoPrevato** [comment]
Hi Tarun, thanks for your kind words. 

Yes, I can share an example that works for Azure Container Registry, it should be straightforward to configure a service connection to Docker Hub, and update my example to use the desired service connection and repository name. 

It uses the official Docker task from Microsoft.

* Note: if you use create a new pipeline in Azure DevOps, and select the "Docker build and publish" template, it will prompt you to select an Azure subscription and an existing ACR, in such case it will also generate a service connection and configure the right ID in the first `azure-pipelines.yml`
* to keep the example simple, I build only the base image and Python image. You can edit to build the ones you need (for NET Core, for example). In my case, I replace the FROM value to incrementally build an agent with all desired tools (e.g. Python, .NET Core tools, Docker).

I am planning to add azure pipelines to my GitHub repository, or add GitHub actions to build the images and maybe publish them to my Docker Hub. But I am not sure because I don't see the value of it: I think nobody should trust images from Docker Hub handled by someone else, for their devops agents. 😊 

```yml
# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self  # This works if you copy my GitHub repo to a private git repo in Azure DevOps

variables:
  dockerRegistryServiceConnection: '<YOUR_SERVICE_CONNECTION_NAME>'
  baseImageName: devopsubuntu18.04
  pythonImageName: devopsubuntu18.04-python
  containerRegistry: 'example.azurecr.io'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push the base image to container registry
      inputs:
        command: buildAndPush
        repository: $(baseImageName)
        dockerfile: $(Build.SourcesDirectory)/ubuntu18.04-base/Dockerfile
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

    # create an alias for the image that was just created, so that it can be easily used by the next Dockerfile
    - bash: docker tag $(containerRegistry)/$(baseImageName):$(tag) $(baseImageName)
      displayName: Create tag $(baseImageName)
    # replace the FROM line of the next Dockerfile, to use our base image name:
    - bash: sed -i "s/FROM\s.*/FROM $(baseImageName)/" Dockerfile
      workingDirectory: $(Build.SourcesDirectory)/ubuntu18.04-python
      displayName: Replace FROM to use base image
    - task: Docker@2
      displayName: Build and push the Python image to container registry
      inputs:
        command: buildAndPush
        repository: $(pythonImageName)
        dockerfile: $(Build.SourcesDirectory)/ubuntu18.04-python/Dockerfile
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
```
